name: Rust
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: sudo apt install -yqq libssh-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
